# Generated by Django 3.1.4 on 2021-01-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('make_name', 'model_name')},
        ),
    ]
